# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker 

trigger:
- develop
- main

variables:
  isDevelop: $[eq(variables['Build.SourceBranch'], 'refs/heads/users/abodineni/newAksDeployment')]
  isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]

  valuesFile: 'values.yaml'
  armServiceConnection: 'CSP-SubscriptionResources'

###########################################################################################
# SIT VARIABLES
###########################################################################################
  keyvaultNameSIT: 'csp-sit'
  
  aksResourceGroupSIT: 'csp-sit'
  aksWestUS3ClusterSIT: 'k8s-csp-sit-westus3'
  aksEastUSClusterSIT: 'k8s-csp-sit-eastus'
  acrServiceConnectionSIT: 'csp-acr-sit'
  aksWestUS3AgentPoolClientIdSIT: '76de7856-8ec1-47b6-9de5-be5b833ef1b3'
  aksEastUSAgentPoolClientIdSIT: '0719a808-41b7-422b-b0bb-2d5e8a95d2ca'
  containerRegistrySIT: 'acrcspsit5769997721069705598.azurecr.io'
  replicaCountSIT: 2

  apimARMServiceConnectionSIT: 'apim-svc'
  apimInstanceNameSIT: 'adarsh-apim'
  apimResourceGroupNameSIT: 'apim'
  apimApiNameSIT: 'CSP API'
  swaggerUrlSIT: 'https://fd-csp-sit-h7f5bmcpfahwfwfr.z01.azurefd.net/csp-api/swagger/v1/swagger.json'
  serviceUrlSIT: 'https://fd-csp-sit-h7f5bmcpfahwfwfr.z01.azurefd.net/csp-api'
  apiPrefixSIT: 'csp-api'
  graphQLSuffixSIT: 'csp-api/graphql'
  apimGraphQLApiNameSIT: 'CSP GraphQL API'
  graphQLServiceUrlSIT: 'https://fd-csp-sit-h7f5bmcpfahwfwfr.z01.azurefd.net/csp-api/graphql'

###########################################################################################
# UAT VARIABLES
###########################################################################################
  keyvaultNameUAT: 'csp-kevt-uat'
  
  aksResourceGroupUAT: 'k8s-rmex-uat'
  aksWestUS2ClusterUAT: 'k8s-rmex-uat-westus2'
  aksEastUS2ClusterUAT: 'k8s-rmex-uat-eastus2'
  acrServiceConnectionUAT: 'RM-UAT-ACR-2021-05-01'
  aksWestUS2AgentPoolClientIdUAT: 'a58c049e-79e7-4637-9a30-3fac1a10a7d9'
  aksEastUS2AgentPoolClientIdUAT: '445dcd8a-9e14-4d88-94fe-4f2990080869'
  containerRegistryUAT: 'acrrmuat10009753473648393486.azurecr.io'
  replicaCountUAT: 2

  apimARMServiceConnectionUAT: 'RM-APIM-20-05'
  apimInstanceNameUAT: 'professionalserviceint'
  apimResourceGroupNameUAT: 'FIPS-INT-RG'
  apimApiNameUAT: 'RMEx CSP UAT API'
  swaggerUrlUAT: 'https://fd-rmex-uat.azurefd.net/rm-csp-api/swagger/v1/swagger.json'
  serviceUrlUAT: 'https://fd-rmex-uat.azurefd.net/rm-csp-api'
  apiPrefixUAT: 'rm-csp-uat-api'

###########################################################################################
# PROD VARIABLES
###########################################################################################
  keyvaultNamePROD: 'csp-kevt-prod'
  
  aksResourceGroupPROD: 'k8s-rmex-prod'
  aksWestUS2ClusterPROD: 'k8s-rmex-prod-westus2'
  aksEastUS2ClusterPROD: 'k8s-rmex-prod-eastus2'
  acrServiceConnectionPROD: 'RM-PROD-ACR-2021-06-01'
  aksWestUS2AgentPoolClientIdPROD: '4ccd4012-1247-40c4-a080-0e8273292d24'
  aksEastUS2AgentPoolClientIdPROD: 'f7d4ffaf-148a-4078-8809-d6b4b38a0073'
  containerRegistryPROD: 'acrrmprod10359943631172522997.azurecr.io'
  replicaCountPROD: 2

  apimARMServiceConnectionPROD: 'RM-APIM-PRD-20-05-21'
  apimInstanceNamePROD: 'professionalservice'
  apimResourceGroupNamePROD: 'FIPS-PROD-RG'
  apimApiNamePROD: 'RMEx CSP API'
  swaggerUrlPROD: 'https://fd-rmex-prod.azurefd.net/rm-csp-api/swagger/v1/swagger.json'
  serviceUrlPROD: 'https://fd-rmex-prod.azurefd.net/rm-csp-api'
  apiPrefixPROD: 'rm-csp-api'

pool:
  vmImage: ubuntu-latest

stages:
- stage: nonprod_import_api_to_apim_sit_stage
  displayName: Import API to APIM for SIT
  jobs:
  - deployment: nonprod_import_api_to_apim_job
    displayName: Import API to APIM in SIT
    environment: 'PS-SD-CSP-SIT'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-apitoapim-template.yml
            parameters:
              apimARMServiceConnection: '$(apimARMServiceConnectionSIT)'
              apimInstanceName: '$(apimInstanceNameSIT)'
              apimResourceGroupName: '$(apimResourceGroupNameSIT)'
              apimApiName: '$(apimApiNameSIT)'
              swaggerUrl: '$(swaggerUrlSIT)'
              serviceUrl: '$(serviceUrlSIT)'
              apiPrefix: '$(apiPrefixSIT)'
              graphQLSuffix: '$(graphQLSuffixSIT)'
              apimGraphQLApiName: '$(apimGraphQLApiNameSIT)'
              graphQLServiceUrl: '$(graphQLServiceUrlSIT)'

- stage: nonprod_build_csp_api_service_uat_stage
  displayName: Build CSP API for UAT
  condition: and(succeeded(), or(eq(variables.isDevelop, true), eq(variables.isMaster, true)))
  dependsOn: nonprod_import_api_to_apim_sit_stage
  jobs:    
  - job: nonprod_build_csp_api_services_job
    displayName: Build csp API for UAT
    steps:
    - template: azure-pipeline-build-template.yml
      parameters:
        serviceConnection: $(armServiceConnection)
        dockerRegistryServiceConnection: $(acrServiceConnectionUAT)        
        keyVaultName: $(keyvaultNameUAT)
  
- stage: nonprod_helm_deploy_uat_westus2_stage
  displayName: Deploy CSP API Service in UAT WestUS2
  condition: and(succeeded(), or(eq(variables.isDevelop, true), eq(variables.isMaster, true)))
  dependsOn: nonprod_build_csp_api_service_uat_stage
  jobs:
  - deployment: nonprod_deploy_csp_api_services_job
    displayName: WestUS2 deployment    
    environment: 'PS-SD-CSP-UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-helm-deploy-template.yml
            parameters:
              environment: 'uat'
              armServiceConnection: $(armServiceConnection)
              aksResourceGroup: $(aksResourceGroupUAT)
              aksCluster: $(aksWestUS2ClusterUAT)
              valuesFile: $(valuesFile)
              containerRegistry: $(containerRegistryUAT)
              aksAgentPoolClientId: $(aksWestUS2AgentPoolClientIdUAT)
              replicaCount: ${{ variables.replicaCountUAT }}

- stage: nonprod_helm_deploy_uat_eastus2_stage
  displayName: Deploy CSP API Service in UAT EastUS2
  condition: and(succeeded(), or(eq(variables.isDevelop, true), eq(variables.isMaster, true)))
  dependsOn: [nonprod_helm_deploy_uat_westus2_stage]
  jobs:
  - deployment: nonprod_deploy_csp_api_services_job
    displayName: EastUS2 deployment
    environment: 'PS-SD-CSP-UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-helm-deploy-template.yml
            parameters:
              environment: 'uat'
              armServiceConnection: $(armServiceConnection)
              aksResourceGroup: $(aksResourceGroupUAT)
              aksCluster: $(aksEastUS2ClusterUAT)
              valuesFile: $(valuesFile)
              containerRegistry: $(containerRegistryUAT)
              aksAgentPoolClientId: $(aksEastUS2AgentPoolClientIdUAT)
              replicaCount: ${{ variables.replicaCountUAT }}

- stage: nonprod_import_api_to_apim_uat_stage
  displayName: Import API to APIM for UAT
  condition: and(succeeded(), or(eq(variables.isDevelop, true), eq(variables.isMaster, true)))
  dependsOn: nonprod_helm_deploy_uat_eastus2_stage
  jobs:
  - deployment: nonprod_import_api_to_apim_job
    displayName: Import API to APIM in UAT
    environment: 'PS-SD-CSP-UAT'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-apitoapim-template.yml
            parameters:
              apimARMServiceConnection: '$(apimARMServiceConnectionUAT)'
              apimInstanceName: '$(apimInstanceNameUAT)'
              apimResourceGroupName: '$(apimResourceGroupNameUAT)'
              apimApiName: '$(apimApiNameUAT)'
              swaggerUrl: '$(swaggerUrlUAT)'
              serviceUrl: '$(serviceUrlUAT)'
              apiPrefix: '$(apiPrefixUAT)'

- stage: prod_build_csp_api_service_stage
  displayName: Build CSP API for PROD
  condition: and(succeeded(), eq(variables.isMaster, true))
  dependsOn: [publish_helm_artifacts_stage, nonprod_import_api_to_apim_uat_stage]
  jobs:    
  - job: prod_build_csp_api_services_job
    displayName: Build csp API for PROD
    steps:
    - template: azure-pipeline-build-template.yml
      parameters:
        serviceConnection: $(armServiceConnection)
        dockerRegistryServiceConnection: $(acrServiceConnectionPROD)        
        keyVaultName: $(keyvaultNamePROD)
  
- stage: prod_helm_deploy_stage_westus2
  displayName: Deploy CSP API Service in PROD WestUS2
  condition: and(succeeded(), eq(variables.isMaster, true))
  dependsOn: prod_build_csp_api_service_stage
  jobs:
  - deployment: prod_deploy_csp_api_services_job
    displayName: WestUS2 deployment    
    environment: 'PS-SD-CSP-PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-helm-deploy-template.yml
            parameters:
              environment: 'Production'
              armServiceConnection: $(armServiceConnection)
              aksResourceGroup: $(aksResourceGroupPROD)
              aksCluster: $(aksWestUS2ClusterPROD)
              valuesFile: $(valuesFile)
              containerRegistry: $(containerRegistryPROD)
              aksAgentPoolClientId: $(aksWestUS2AgentPoolClientIdPROD)
              replicaCount: ${{ variables.replicaCountPROD }}

- stage: prod_helm_deploy_stage_eastus2
  displayName: Deploy CSP API Service in PROD EastUS2
  condition: and(succeeded(), eq(variables.isMaster, true))
  dependsOn: [prod_helm_deploy_stage_westus2]
  jobs:
  - deployment: prod_deploy_csp_api_services_job
    displayName: EastUS2 deployment
    environment: 'PS-SD-CSP-PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-helm-deploy-template.yml
            parameters:
              environment: 'Production'
              armServiceConnection: $(armServiceConnection)
              aksResourceGroup: $(aksResourceGroupPROD)
              aksCluster: $(aksEastUS2ClusterPROD)
              valuesFile: $(valuesFile)
              containerRegistry: $(containerRegistryPROD)
              aksAgentPoolClientId: $(aksEastUS2AgentPoolClientIdPROD)
              replicaCount: ${{ variables.replicaCountPROD }}

- stage: prod_import_api_to_apim_stage
  displayName: Import API to APIM for PROD
  condition: and(succeeded(), eq(variables.isMaster, true))
  dependsOn: prod_helm_deploy_stage_eastus2
  jobs:
  - deployment: prod_import_api_to_apim_job
    displayName: Import API to APIM in PROD
    environment: 'PS-SD-CSP-PROD'
    strategy:
      runOnce:
        deploy:
          steps:
          - template: azure-pipeline-apitoapim-template.yml
            parameters:
              apimARMServiceConnection: '$(apimARMServiceConnectionPROD)'
              apimInstanceName: '$(apimInstanceNamePROD)'
              apimResourceGroupName: '$(apimResourceGroupNamePROD)'
              apimApiName: '$(apimApiNamePROD)'
              swaggerUrl: '$(swaggerUrlPROD)'
              serviceUrl: '$(serviceUrlPROD)'
              apiPrefix: '$(apiPrefixPROD)'
